# Report unpushed changes to any project.
for repo in $(find "${HOME}/Projects/"* -maxdepth 0 -type d -not -path "*/venv*"); do
    [[ -d "${repo}/.git" ]] && {
        cd "${repo}" && [[ ! $(git status --porcelain | wc -l) -eq "0" ]] && {
            echo "Changes detected in $(basename ${repo})..."
        }
    }
done

# Output installed pip packages.
if [[ -d "${HOME}/Projects" ]] && [[ ! -z "${python_ver}" ]]
 then python -m pip freeze > "${HOME}/Projects/venv${python_ver}/requirements.txt"
fi
